if(NOT DEFINED FORGE OR NOT DEFINED SOURCE_DIR OR NOT DEFINED TEST_DIR)
    message(FATAL_ERROR "FORGE, SOURCE_DIR and TEST_DIR are required")
endif()
file(MAKE_DIRECTORY "${TEST_DIR}")

function(expect_cli name expected_status expected_text)
    execute_process(COMMAND "${FORGE}" ${ARGN}
        WORKING_DIRECTORY "${TEST_DIR}"
        RESULT_VARIABLE status OUTPUT_VARIABLE out ERROR_VARIABLE err TIMEOUT 10)
    if(NOT "${status}" STREQUAL "${expected_status}")
        message(FATAL_ERROR "${name}: expected exit ${expected_status}, got ${status}\n${out}${err}")
    endif()
    if(expected_status EQUAL 0)
        if(NOT err STREQUAL "")
            message(FATAL_ERROR "${name}: unexpected stderr: ${err}")
        endif()
        set(actual "${out}")
    else()
        set(actual "${err}")
    endif()
    if(NOT actual MATCHES "${expected_text}")
        message(FATAL_ERROR "${name}: expected '${expected_text}', got '${actual}'")
    endif()
endfunction()

set(hello "${SOURCE_DIR}/examples/hello.fg")
expect_cli(help 0 "Usage:" --help)
expect_cli(short_help 0 "Usage:" -h)
expect_cli(version 0 "Forge ${EXPECTED_VERSION}" --version)
expect_cli(no_arguments 1 "Usage:")
expect_cli(check 0 "" --check "${hello}")
expect_cli(unknown_option 1 "unknown option '--chek'" --check "${hello}" --chek)
foreach(option -o --header --forge-root --lib-dir --cc -I -l -L)
    expect_cli("missing_${option}" 1 "requires a value" --check "${hello}" "${option}")
    expect_cli("flag_as_${option}" 1 "requires a value" "${option}" --check "${hello}")
endforeach()
expect_cli(multiple_inputs 1 "multiple input files" --check missing.fg "${hello}")
expect_cli(missing_file 1 "cannot open" --check missing.fg)
expect_cli(library_header 1 "requires --header" --lib "${hello}")
expect_cli(symbols 0 "\\[" --symbols-json "${hello}")
file(WRITE "${TEST_DIR}/-hello.fg" "process main { println(42); }\n")
expect_cli(option_separator 0 "" --check -- -hello.fg)
message(STATUS "CLI smoke checks passed")
